[{"count": 0, "tags": [], "creator": "SNeelakantan_C@zaplet.com", "attachment_id": null, "text": "Anties,\n\nI had logged a bug last week or so that the BuildEventListener did not\ncatch exceptions even on a failed copy, but I was informed that <copy> didn't \nthrow exception with Ant 1.3 and I was asked to upgraded to Ant 1.4.\nI picked up a nightly build (2001-07-25) and I have the same problem with that \none too.\nI am basically doing a <copy file=\"non-existent1.txt\" tofile=\"non-\nexistent2.txt\" /> and I get the message, \"Could not find file to copy\", but it \ndoesn't set an exception with my listener class.\nI am finding it difficult to validate whether my tasks ran successfully or not \nbecause of this.\n\nI would appreciate any alternative solution too to accomplish this task.\n\nPlease reply ASAP if possible.\n\nThanks and regards,\nShanker", "id": 4198, "time": "2001-07-31T19:38:59Z", "bug_id": 2942, "creation_time": "2001-07-31T19:38:59Z", "is_private": false}, {"count": 1, "tags": [], "bug_id": 2942, "text": "Created attachment 377\nSimple listener", "id": 4210, "attachment_id": 377, "creator": "conor@apache.org", "creation_time": "2001-08-01T06:26:33Z", "time": "2001-08-01T06:26:33Z", "is_private": false}, {"count": 2, "tags": [], "bug_id": 2942, "text": "OK, I have attached a simple listener implementation. I have a simple buikld \nfile which attempts to copy a non-existent file and another target which does \nnothing. These are the reuslts for me when I run this. Note the last line of \noutput in each run and in particular the presence of the exception in the \nfailure case\n\nF:\\antdev\\bugs\\bug2942>ant -listener TestListener ok\nBuildfile: build.xml\nListener: build started\n\nok:\nListener: target started\nListener: target finished\n\nBUILD SUCCESSFUL\n\nTotal time: 1 second\nBuild finished without error\nF:\\antdev\\bugs\\bug2942>ant -listener TestListener\nBuildfile: build.xml\nListener: build started\n\nmain:\nListener: target started\n     [copy] Listener: task started\n     [copy] Could not find file F:\\antdev\\bugs\\bug2942\\foo to copy.\nListener: task finished\nListener: target finished\n\nBUILD FAILED\n\nF:\\antdev\\bugs\\bug2942\\build.xml:3: Could not find file F:\\antdev\\bugs\\bug2942\n\\foo to copy.\n\nTotal time: 1 second\nListener: build finished with exception = org.apache.tools.ant.BuildException\nF:\\antdev\\bugs\\bug2942>", "id": 4211, "time": "2001-08-01T06:29:27Z", "creator": "conor@apache.org", "creation_time": "2001-08-01T06:29:27Z", "is_private": false, "attachment_id": null}, {"count": 3, "tags": [], "creator": "SNeelakantan_C@zaplet.com", "attachment_id": null, "text": "Thanks Conor for your prompt response.\n\nI am not sure if I am seeing normal behaviour from the BuildEvent Listener.\nHere is what I tried.\n\nC:\\play>ant -listener BuildValidate -f test.xml\n\nC:\\play>type test.xml\n<project default=\"X\" >\n        <target name=\"X\">\n                <copy file=\"doesnotexist.txt\" tofile=\"doesnotexist2.txt\" />\n        </target>\n</project>\n\nC:\\play>dir does*\n Volume in drive C has no label.\n Volume Serial Number is 07D1-0208\n\n Directory of C:\\play\n\nFile Not Found\n\nC:\\play>ant -listener BuildValidate -f test.xml\nBuildfile: test.xml\n\nX:\n     [copy] Could not find file C:\\play\\doesnotexist.txt to copy.\nTask has completed successfully   \n\n<mycomment> getException() = null in taskFinished() in BuildValidate</mycomment>\n\nTarget has finished successfully\n\n<mycomment> getException() = null in targetFinished() in \nBuildValidate</mycomment>\n\nBUILD SUCCESSFUL\n\nTotal time: 1 second\n\nC:\\play>type test.xml\n<project default=\"X\" >\n        <target name=\"X\">\n                <copy file=\"doesnotexist.txt\" tofile=\"doesnotexist2.txt\" />\n                <ant antfile=\"test.xml\" target=\"build\" />\n        </target>\n</project>\n\nC:\\play>ant -listener BuildValidate -f test.xml\nBuildfile: test.xml\n\nX:\n     [copy] Could not find file C:\\play\\doesnotexist.txt to copy.\nTask has completed successfully\nTask has completed successfully\nTarget has finished unsuccessfully\n<mycomment> Both tasks are successful, but the target isn't! </mycomment>\n\n\nBUILD FAILED\n\nC:\\play\\test.xml:4: Target `build' does not exist in this project.\n\nTotal time: 1 second\n\n-------------\nI think, an unsuccessful task is not caught in the taskFinished() method, but\nis caught in the targetFinished() method which is why you were able to catch \nthe exception since you implemented it in the targetFinished() method.\nI intend to catch errors in individual tasks within a target.\n\nCorrect me if I am mistaken.\n\nThanks,\nShankar", "id": 4218, "time": "2001-08-01T11:11:53Z", "bug_id": 2942, "creation_time": "2001-08-01T11:11:53Z", "is_private": false}, {"count": 4, "tags": [], "bug_id": 2942, "attachment_id": null, "text": "Thanks for persisting with this. I found the bug - exceptions were not being \nset in the event for tasks. Please try the next nightly build\n2001-08-03\n", "id": 4232, "time": "2001-08-02T05:23:09Z", "creator": "conor@apache.org", "creation_time": "2001-08-02T05:23:09Z", "is_private": false}]